import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
public class EntityManagerImpl {
    private Connection connection;

    public EntityManagerImpl() {
        try {
            this.connection = DriverManager.getConnection("jdbc:hsqldb:mem:mymemdb", "SA", "");
            this.createTable();
        } catch (SQLException e) {
            throw new RuntimeException("Problème de connexion à la base de données", e);
        }
    }
    private void createTable() throws SQLException {
        String sql = "CREATE TABLE Club (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version INT, fabricant VARCHAR(255), poids DOUBLE)";
        connection.createStatement().executeUpdate(sql);
    }
    public <T> T merge(T entity) {
        return entity;
    }
}