package org.example;

import java.lang.reflect.Field;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class EntityManagerImpl {

    public Connection connection=null;

    public EntityManagerImpl() {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
            this.connection = DriverManager.getConnection("jdbc:hsqldb:mem:database", "sa", "");
            System.out.println("test : "+connection);
            this.createTable();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createTable() throws SQLException {
            String sql = "CREATE TABLE Club (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version INT, fabricant VARCHAR(255), poids DOUBLE)";
            this.connection.createStatement().executeUpdate(sql);
    }



    public void persist(Object entity) {
        try {
            String sql = "INSERT INTO Club (fabricant, poids) VALUES (?, ?)";
            PreparedStatement pstmt = connection.prepareStatement(sql);
            Field fabricantField = entity.getClass().getDeclaredField("fabricant");
            fabricantField.setAccessible(true);
            pstmt.setString(1, (String) fabricantField.get(entity));

            Field poidsField = entity.getClass().getDeclaredField("poids");
            poidsField.setAccessible(true);
            pstmt.setDouble(2, (Double) poidsField.get(entity));

            pstmt.executeUpdate();
        } catch (Exception e) {
            throw new RuntimeException("Problème de persistance de l'entité", e);
        }
    }


}